/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2015-10-14 14:18:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.registered;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Encryption.Base64;
import java.util.Arrays;

public final class registered_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.Arrays");
    _jspx_imports_classes.add("Encryption.Base64");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"../error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<title>GC博客用户注册</title>\n");
      out.write("<script id=\"jquery_183\" type=\"text/javascript\" class=\"library\" src=\"js/jquery-1.8.3.min.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<!-- java start -->\n");

	request.setCharacterEncoding("utf-8");
	String errmsg = "";
	System.out.println("~"+request.getParameter("Rm")+"~");
	if(request.getParameter("Rm")!=null){
		errmsg = request.getParameter("Rm");
		String[] errmsga = errmsg.split(" ");
		errmsg ="";
		
		if(errmsga[0].equals("0")){
			errmsg += "该邮箱已经被注册,请重新填写 \\n";
		}else{
			if(errmsga[0].equals("-1"))
				errmsg += "邮箱格式不符，请重新填写 \\n";
			if(errmsga[0].equals("-2"))
				errmsg += "邮箱不能为空 \\n";
			if(errmsga[1].equals("-2"))
				errmsg += "昵称不能为空 \\n";
			if(errmsga[2].equals("-2"))
				errmsg += "密码需要6-16个字符 \\n";
			if(errmsga[2].equals("0"))
				errmsg += "密码不能为空 \\n";
			if(errmsga[3].equals("-2"))
				errmsg += "两次密码输入不一致 \\n";
		}
	}
	System.out.print(errmsg);

      out.write("\n");
      out.write("<!-- java end -->\n");
      out.write("<div class=\"back\">\n");
      out.write("<div id=\"top\"><h1>用户注册</h1></div>\n");
      out.write("<div class=\"form-bak\">\n");
      out.write("<form method=\"post\" action=\"/myblog/RegisteredDo\" >\n");
      out.write("<div class=\"left\">\n");
      out.write("<div class=\"line\" id=\"line_account\">\n");
      out.write("<div class=\"info\">\n");
      out.write("<strong>邮箱(Email)</strong>\n");
      out.write("<span class=\"tips\">邮箱就是账号</span>\n");
      out.write("</div>\n");
      out.write("<div class=\"input\">\n");
      out.write("<input type=\"text\" name=\"email\" id=\"account\" onblur=\"v_account();\" onkeyup=\"v_account();\"/>\n");
      out.write("<div class=\"none\">\n");
      out.write("<span></span>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"line\" id=\"line_name\">\n");
      out.write("<div class=\"info\">\n");
      out.write("<strong>昵称(Nick)</strong>\n");
      out.write("<span class=\"tips\">只能由数字、文字或下划线组成<br />最多32个字符</span>\n");
      out.write("</div>\n");
      out.write("<div class=\"input\">\n");
      out.write("<input type=\"text\" name=\"nick\" id=\"name\" onblur=\"v_name();\" onkeyup=\"v_name();\" />\n");
      out.write("<div class=\"none\">\n");
      out.write("<span></span>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"line\" id=\"line_password\">\n");
      out.write("<div class=\"info\">\n");
      out.write("<strong>密码(PassW)</strong>\n");
      out.write("<span class=\"tips\">6至16个字符</span>\n");
      out.write("</div>\n");
      out.write("<div class=\"input\">\n");
      out.write("<input type=\"password\" name=\"password\" id=\"password\" onblur=\"v_password();\" onkeyup=\"v_password();\" />\n");
      out.write("<div class=\"none\">\n");
      out.write("<span></span>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"line\" id=\"line_repeat\">\n");
      out.write("<div class=\"info\">\n");
      out.write("<strong>确认密码</strong>\n");
      out.write("<span class=\"tips\">再次输入密码</span>\n");
      out.write("</div>\n");
      out.write("<div class=\"input\">\n");
      out.write("<input type=\"password\" name=\"repeatpassword\" id=\"repeat\" onblur=\"v_repeat();\" onkeyup=\"v_repeat();\" />\n");
      out.write("<div class=\"none\">\n");
      out.write("<span></span>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"right\">\n");
      out.write("<input type=\"submit\" id=\"submit\" value=\"完成注册\" disabled=\"disabled\"/>\n");
      out.write("<div class=\"readagreement-wrap\" onclick=\"onReadAgreementClick();\">\n");
      out.write("<input type=\"checkbox\" name=\"agree\" id=\"agree\" onchange=\"v_submitbutton();\" />\n");
      out.write("同意《<a id=\"readagreement\" href=\"#agreement\" onclick=\"showAgreement();\" title=\"查看用户使用协议\">用户使用协议</a>》\n");
      out.write("</div>\n");
      out.write("<div>已有账号？<a href=\"../login/login.jsp\">直接登录</a></div>\n");
      out.write("<div>不想注册？<a href=\"../nav/index.jsp\">返回博客</a></div>\n");
      out.write("<div>忘记密码？<a href=\"#\">联系管理员</a></div>\n");
      out.write("</div>\n");
      out.write("</form>\n");
      out.write("</div>\n");
      out.write("<div id=\"agreement\" class=\"agreement\" style=\"display:none;\">\n");
      out.write("<h1>用户使用协议</h1>\n");
      out.write("<iframe src=\"\"></iframe>\n");
      out.write("<input type=\"button\" value=\"同意\" onclick=\"agree();\"/>\n");
      out.write("<a href=\"#\" class=\"backtotop\" >返回顶部</a>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("<style>* { font-family:\"微软雅黑\",\"黑体\",\"宋体\"; color:#333;}\n");
      out.write("a {color:#069;}\n");
      out.write("body {margin:0; padding:0; background:#ddd;  background: url('img/registered_bg.jpg');\n");
      out.write("  background-size: 100%,auto;}\n");
      out.write(".form-bak {width:800px; height:400px; margin:40px auto; background:#eee; border-radius:10px; box-shadow:0 2px 8px #999;}\n");
      out.write(".left {float:left; width:500px; height:400px;}\n");
      out.write(".line {width:100%; height:80px; margin:16px 0 0 0;}\n");
      out.write(".info {float:left; height:100%; width:200px;}\n");
      out.write(".info strong, .info span {display:block; text-align:right;}\n");
      out.write(".info strong {font-size:24px; line-height:36px; margin-top:10px; color:#333; }\n");
      out.write(".info span {font-size:12px; line-height:24px; color:#666; font-family:\"微软雅黑\",\"宋体\"; }\n");
      out.write(".input input {background:none; border:none; outline:none; font-size:18px; line-height:40px; height:40px; width:240px; padding:9px 0 9px 9px; border-radius:10px;}\n");
      out.write(".input {float:right; width:278px; height:58px; background:#f6f6f6; border:1px solid #999; border-radius:10px; box-shadow:inset 0 2px 5px #999; margin:10px 0; position:relative; }\n");
      out.write(".error,.corect {height:20px; width:20px; position:absolute; top:19px; right:9px; background:url(\"js/ICON_20.svg\") no-repeat 0 -20px;}\n");
      out.write(".error span {display:block; position:absolute; top:30px; right:20px; background:#fcc; border:1px solid #f33; font-size:12px; line-height:16px; color:#600; padding:6px 10px 4px 10px; border-radius:5px; opacity:.8; white-space:nowrap; overflow:hidden;}\n");
      out.write(".corect {background-position:0 0;}\n");
      out.write(".corect span{display:none;}\n");
      out.write(".none {display:none;}\n");
      out.write("\n");
      out.write(".right {float:right; width:260px; height:360px; margin:20px 0 0 0; border-left:1px solid #ccc;}\n");
      out.write("input[type=submit] {background:none; border:none; outline:none; margin:0; padding:0; cursor:pointer;\n");
      out.write("font-size:40px; height:200px; width:200px; background:#369; margin:20px 30px 0 30px; color:#eee;}\n");
      out.write("input[type=submit]:disabled {background:#999; cursor:no-drop;}\n");
      out.write(".right div { margin:0 30px; width:200px; height:30px; line-height:30px; text-align:center;}\n");
      out.write(".readagreement-wrap {margin:20px 30px!important; outline:1px solid #f99;}\n");
      out.write("\n");
      out.write("#top h1 {font-size:30px; line-height:40px; padding:10px; text-align:center;}\n");
      out.write(".agreement,#top {width:800px; margin:20px auto; background:#eee; border-radius:10px; box-shadow:0 2px 8px #999; text-align:center;}\n");
      out.write(".agreement h1 {display:block; font-size:24px; line-height:30px; padding:20px 20px 10px 20px; margin:0; color:#333; text-align:center;}\n");
      out.write(".agreement iframe { width:760px; min-height:400px; margin:0 20px 20px 20px; border:none; outline:none;}\n");
      out.write(".agreement .backtotop {display:block; line-height:20px; padding:10px; text-align:center;}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("$(document).ready(\n");
      out.write("\tfunction(){\n");
      out.write("\t\tvar err = '");
      out.print(errmsg );
      out.write("';\n");
      out.write("\t\tif(err != '')\n");
      out.write("\t\t\talert(err);\n");
      out.write("\t}\n");
      out.write(");\n");
      out.write("function enableSubmit(bool){\n");
      out.write("if(bool)$(\"#submit\").removeAttr(\"disabled\");\n");
      out.write("else $(\"#submit\").attr(\"disabled\",\"disabled\");\n");
      out.write("}\n");
      out.write("function v_submitbutton(){\n");
      out.write("if($(\"#agree\").attr(\"checked\")!=\"checked\") {\n");
      out.write("enableSubmit(false);\n");
      out.write("$(\".readagreement-wrap\").css(\"outline\",\"1px solid #f99\");\n");
      out.write("return;\n");
      out.write("}else{$(\".readagreement-wrap\").css(\"outline\",\"1px solid #9f9\");}\n");
      out.write("for(f in flags) if(!flags[f]) {enableSubmit(false); return;}\n");
      out.write("enableSubmit(true);\n");
      out.write("}\n");
      out.write("function showAgreement(){\n");
      out.write("$(\"#readagreement\").removeAttr(\"onclick\");\n");
      out.write("$(\"#agreement\").show();\n");
      out.write("$(\"#agreement iframe\").attr(\"src\",\"http://www.baidu.com\");//此处为链接地址\n");
      out.write("}\n");
      out.write("function agree(){\n");
      out.write("$(\"#agreement\").hide();\n");
      out.write("$(\"#readagreement\").attr(\"onclick\",\"showAgreement();\");\n");
      out.write("if($(\"#agree\").attr(\"checked\")!=\"checked\") $(\"#agree\").trigger(\"click\");\n");
      out.write("}\n");
      out.write("function onReadAgreementClick(){\n");
      out.write("return;\n");
      out.write("if($(\"#agree\").attr(\"checked\")){\n");
      out.write("$(\"#agree\").removeAttr(\"checked\");\n");
      out.write("}else{\n");
      out.write("$(\"#agree\").attr(\"checked\",\"checked\");\n");
      out.write("}\n");
      out.write("v_submitbutton();\n");
      out.write("}\n");
      out.write("var flags = [false,false,false,false];\n");
      out.write("//邮箱验证，网上找到的正则\n");
      out.write("var RegEmail = /^([a-zA-Z0-9]+[_|\\_|\\.]?)*[a-zA-Z0-9]+@([a-zA-Z0-9]+[_|\\_|\\.]?)*[a-zA-Z0-9]+\\.[a-zA-Z]{2,3}$/;\n");
      out.write("function lineState(name,state,msg){\n");
      out.write("if(state==\"none\"){$(\"#line_\"+name+\" .input div\").attr(\"class\",\"none\"); return;}\n");
      out.write("if(state==\"corect\"){$(\"#line_\"+name+\" .input div\").attr(\"class\",\"corect\");return;}\n");
      out.write("$(\"#line_\"+name+\" .input span\").text(msg);$(\"#line_\"+name+\" .input div\").attr(\"class\",\"error\");\n");
      out.write("}\n");
      out.write("function v_account(){\n");
      out.write("var account = $(\"#account\").val();\n");
      out.write("if(!RegEmail.test(account)) {lineState(\"account\",\"error\",\"邮箱格式不正确\"); flags[0]=false;enableSubmit(false);}\n");
      out.write("else{lineState(\"account\",\"corect\",\"\");flags[0] = true;}\n");
      out.write("v_submitbutton();\n");
      out.write("}\n");
      out.write("function v_name(){\n");
      out.write("var name = $(\"#name\").val();\n");
      out.write("if(name.length==0) {lineState(\"name\",\"error\",\"不得为空\"); flags[1]=false;}\n");
      out.write("else{\n");
      out.write("if(name.length>32) {lineState(\"name\",\"error\",\"必须少于32个字符\"); flags[1]=false;}\n");
      out.write("else{lineState(\"name\",\"corect\",\"\"); flags[1] = true;}\n");
      out.write("}\n");
      out.write("v_submitbutton();\n");
      out.write("}\n");
      out.write("function v_password(){\n");
      out.write("var password = $(\"#password\").val();\n");
      out.write("if(password.length<6) {lineState(\"password\",\"error\",\"必须多于或等于6个字符\"); flags[2]=false;}\n");
      out.write("else{\n");
      out.write("if(password.length>16){lineState(\"password\",\"error\",\"必须少于或等于16个字符\"); flags[2]=false;}\n");
      out.write("else{\n");
      out.write("lineState(\"password\",\"corect\",\"\");\n");
      out.write("flags[2] = true;\n");
      out.write("}\n");
      out.write("}\n");
      out.write("v_repeat();\n");
      out.write("v_submitbutton();\n");
      out.write("}\n");
      out.write("function v_repeat(){\n");
      out.write("if(!flags[2]) {lineState(\"repeat\",\"none\",\"\"); return;}\n");
      out.write("if($(\"#password\").val()!=$(\"#repeat\").val()) {lineState(\"repeat\",\"error\",\"密码不一致\"); flags[3]=false;}\n");
      out.write("else{\n");
      out.write("lineState(\"repeat\",\"corect\",\"\");\n");
      out.write("flags[3] = true;\n");
      out.write("}\n");
      out.write("v_submitbutton();\n");
      out.write("}\n");
      out.write("\n");
      out.write("function adaptValue(){\n");
      out.write("return true;\n");
      out.write("}</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
