/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2015-10-15 12:47:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.back;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import dao.MessDao;
import dao.ReplyDao;
import dao.JournalDao;
import dao.AdminDao;
import dao.UserDao;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.sun.jmx.snmp.Timestamp;

public final class back_005findex_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("dao.MessDao");
    _jspx_imports_classes.add("dao.UserDao");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("com.sun.jmx.snmp.Timestamp");
    _jspx_imports_classes.add("dao.AdminDao");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("dao.ReplyDao");
    _jspx_imports_classes.add("dao.JournalDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\n");
      out.write("<title>Gc微博后台</title>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("<!-- Bootstrap -->\n");
      out.write("<link href=\"css/bootstrap.min.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("<link href=\"css/bootstrap-theme.min.css\" rel=\"stylesheet\" media=\"screen\">\n");
      out.write("\n");
      out.write("<!-- Bootstrap Admin Theme -->\n");
      out.write("<link href=\"css/bootstrap-admin-theme.css\" rel=\"stylesheet\"\n");
      out.write("\tmedia=\"screen\">\n");
      out.write("\n");
      out.write("<!-- Vendors -->\n");
      out.write("<link href=\"vendors/easypiechart/jquery.easy-pie-chart.css\"\n");
      out.write("\trel=\"stylesheet\" media=\"screen\">\n");
      out.write("<link href=\"vendors/easypiechart/jquery.easy-pie-chart_custom.css\"\n");
      out.write("\trel=\"stylesheet\" media=\"screen\">\n");
      out.write("\n");
      out.write("<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->\n");
      out.write("<!--[if lt IE 9]>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/html5shiv.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"js/respond.min.js\"></script>\n");
      out.write("    <![endif]-->\n");
      out.write("</head>\n");
      out.write("<body class=\"bootstrap-admin-with-small-navbar\">\n");
      out.write("\t<nav class=\"navbar navbar-default navbar-inverse navbar-fixed-top \"\n");
      out.write("\t\trole=\"navigation\">\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<!-- Brand and toggle get grouped for better mobile display -->\n");
      out.write("\t\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\n");
      out.write("\t\t\t\t\tdata-target=\"#bs-example-navbar-collapse-1\">\n");
      out.write("\t\t\t\t\t<span class=\"sr-only\">Toggle navigation</span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\n");
      out.write("\t\t\t\t\t\tclass=\"icon-bar\"></span>\n");
      out.write("\t\t\t\t</button>\n");
      out.write("\t\t\t\t<a class=\"navbar-brand\" href=\"#\">Gc微博后台</a>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- Collect the nav links, forms, and other content for toggling -->\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\"\n");
      out.write("\t\t\t\tid=\"bs-example-navbar-collapse-1\">\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"#\">首页</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"back_help.jsp\">使用介绍</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\t<form class=\"navbar-form navbar-left\" role=\"search\">\n");
      out.write("\t\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" placeholder=\"请输入内容\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\">搜索</button>\n");
      out.write("\t\t\t\t</form>\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\t\t<li class=\"dropdown\"><a href=\"#\" class=\"dropdown-toggle\"\n");
      out.write("\t\t\t\t\t\tdata-toggle=\"dropdown\">管理员<b class=\"caret\"></b></a>\n");
      out.write("\t\t\t\t\t\t<ul class=\"dropdown-menu\">\n");
      out.write("\t\t\t\t\t\t\t<li><a href=\"/myblog/AdminSessionLogout\">退出登录</a></li>\n");
      out.write("\t\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<!-- /.navbar-collapse -->\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<!-- left, vertical navbar & content -->\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<!-- left, vertical navbar -->\n");
      out.write("\t\t\t<div class=\"col-md-2 bootstrap-admin-col-left\">\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-collapse collapse bootstrap-admin-navbar-side\">\n");
      out.write("\t\t\t\t\t<li class=\"active\"><a href=\"back_index.jsp\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 首页</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"back_about.jsp\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 关于我们</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"disabled\"><a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 日历</a>\n");
      out.write("\t\t\t\t\t<!-- calendar.html --></li>\n");
      out.write("\t\t\t\t\t<li class=\"disabled\"><a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 统计图表</a>\n");
      out.write("\t\t\t\t\t<!-- stats.html --></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"back_journal_release.jsp\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 日志发布</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"back_journal_admin.jsp\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 日志管理</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"back_users.jsp\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 用户管理</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"back_message.jsp\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 留言管理</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"back_image.jsp\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 图片管理</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"back_admin_information.jsp\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 账户中心</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 留白1</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 留白2</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 留白3</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\"><i\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></i> 留白4</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t<!-- content -->\n");
      out.write("\t\t\t<div class=\"col-md-10\">\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"alert alert-success bootstrap-admin-alert\">\n");
      out.write("\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"alert\">×</button>\n");
      out.write("\t\t\t\t\t\t<h4>成功登陆后台页面的时间为:&nbsp&nbsp&nbsp&nbsp\n");
      out.write("\t\t\t\t\t\t\t");
 
								SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
								out.print(sdf.format(new Date()));
								
								//定义各个最大限度
								//注册用户最大值为5000
								double maxUser = 500;
								//Admin用户最大值为10
								double maxAdmin = 10;
								//发表日志最大值为500
								double maxArticle = 500;
								//日志回复总数最大值为5000
								double maxReply = 5000;
								//留言板最大一级留言数100
								double maxFirstMessage = 100;
								//留言板最大二级留言数1000
								double maxSecoundMessage = 1000;
								//最大网页点击量1000
								double maxClick = 1000;
								//最大IP访问数500
								double maxIp = 100;
							
      out.write("\n");
      out.write("\t\t\t\t\t\t</h4>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<div class=\"row\">\n");
      out.write("\t\t\t\t\t<div class=\"panel panel-default bootstrap-admin-no-table-panel\">\n");
      out.write("\t\t\t\t\t\t<div class=\"panel-heading\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"text-muted bootstrap-admin-box-title\">统计</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"pull-right\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"badge\"></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"bootstrap-admin-panel-content bootstrap-admin-no-table-panel-content collapse in\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"");
out.print((1.0*UserDao.countUserSum()/maxUser)*100); 
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(UserDao.countUserSum());
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">注册用户</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"");
      out.print(((1.0*AdminDao.countAdminSum()/maxAdmin)*100));
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(AdminDao.countAdminSum() );
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">Admin用户</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"");
      out.print(((1.0*JournalDao.countJournalSum()/maxArticle)*100));
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(JournalDao.countJournalSum());
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">发表日志</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"");
      out.print(((1.0*ReplyDao.countReplySum()/maxReply)*100) );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(ReplyDao.countReplySum() );
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">日志留言</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"bootstrap-admin-panel-content bootstrap-admin-no-table-panel-content collapse in\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"");
      out.print(((1.0*MessDao.countFirstMess()/maxFirstMessage)*100) );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(MessDao.countFirstMess() );
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">一级留言</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"");
      out.print(((1.0*MessDao.countSecoundMess()/maxSecoundMessage)*100) );
      out.write("\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      out.print(MessDao.countSecoundMess() );
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">二级留言</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"50\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t50%\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">网页点击量</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"50\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t50%\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">浏览Ip量</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"bootstrap-admin-panel-content bootstrap-admin-no-table-panel-content collapse in\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"50\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t50%\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">预留1</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"50\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t50%\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">预留2</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"50\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t50%\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">预留3</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-3\">\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"easyPieChart\" data-percent=\"50\"\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width: 110px; height: 110px; line-height: 110px;\">\n");
      out.write("\t\t\t\t\t\t\t\t\t50%\n");
      out.write("\t\t\t\t\t\t\t\t\t<canvas width=\"110\" height=\"110\"></canvas>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"chart-bottom-heading\">\n");
      out.write("\t\t\t\t\t\t\t\t\t<span class=\"label label-info\">预留4</span>\n");
      out.write("\t\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<hr/>\n");
      out.write("\t\t\t\t\t\t<br/>\n");
      out.write("\t\t\t\t\t\t<br/>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"row\">\n");
      out.write("\t\t\t<hr>\n");
      out.write("\t\t\t<footer role=\"contentinfo\">\n");
      out.write("\t\t\t<p>\n");
      out.write("\t\t\t\t&copy; 2015 <a href=\"#\" target=\"_blank\">Gc</a>\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t</footer>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\n");
      out.write("\t<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"http://code.jquery.com/jquery-2.0.3.min.js\"></script>\n");
      out.write("\n");
      out.write("\t<!-- Include all compiled plugins (below), or include individual files as needed -->\n");
      out.write("\t<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"js/twitter-bootstrap-hover-dropdown.min.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"vendors/easypiechart/jquery.easy-pie-chart.js\"></script>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\t\t$(function() {\n");
      out.write("\t\t\t// Easy pie charts\n");
      out.write("\t\t\t$('.easyPieChart').easyPieChart({\n");
      out.write("\t\t\t\tanimate : 1000\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
