/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.27
 * Generated at: 2015-11-22 13:28:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.jsp.prompt;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class prompt_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"content-type\" content=\"text/html; charset=utf-8\" />\n");
      out.write("<title>提示页面</title>\n");
      out.write("<meta name=\"keywords\" content=\"\" />\n");
      out.write("<meta name=\"description\" content=\"\" />\n");
      out.write("<link href=\"default.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body {\n");
      out.write("\tbackground-color: #000;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div id=\"header\">\n");
      out.write("\t<h1 style=\"margin-left: 30px;\"><a >Gc blog </a></h1>\n");
      out.write("</div>\n");
      out.write("<div id=\"pages\">\n");
      out.write("\t<h2>Pages</h2>\n");
      out.write("\t<ul>\n");
      out.write("\t\t<li><a id=\"page1\" href=\"../nav/index.jsp\">博客主页</a></li>\n");
      out.write("\t\t<li><a id=\"page2\" href=\"../Journal/Journal.jsp\">博客日志</a></li>\n");
      out.write("\t\t<li><a id=\"page3\" href=\"../update/update.jsp\">TA</a></li>\n");
      out.write("\t\t<li><a id=\"page4\" href=\"../information/information.jsp\">博主信息</a></li>\n");
      out.write("\t\t<li><a id=\"page5\" href=\"../editor/messagebox.jsp\">留言板</a></li>\n");
      out.write("\t\t<li><a id=\"page6\" href=\"../login/login.jsp\">登陆/注册</a></li>\n");
      out.write("\t</ul>\n");
      out.write("</div>\n");
      out.write("<div id=\"content\">\n");
      out.write("\t<div id=\"posts\">\n");
      out.write("\t\t<div class=\"post\">\n");
      out.write("\t\t\t<h2 class=\"title\">该页面功能正在开发ing......</h2>\n");
      out.write("\t\t\t<h3 class=\"posted\">The page function is being developed....</h3>\n");
      out.write("\t\t\t<div class=\"story\">\n");
      out.write("\t\t\t\t<p><h1><em><strong>该页面正在开发,敬请关注.</strong></em></h1> </p>\n");
      out.write("\t\t\t\t<p><h4><em>为了补偿给您带来的不便,我们在下面将会给您提供方便的连接.</em></h4> </p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"meta\">\n");
      out.write("\t\t\t\t<p><a>2015-10-17 15:00</a></p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"post\">\n");
      out.write("\t\t\t<h2 class=\"title\">友情连接</h2>\n");
      out.write("\t\t\t<h3 class=\"posted\">Provided Links......</h3>\n");
      out.write("\t\t\t<div class=\"story\">\n");
      out.write("\t\t\t\t<p>link list:</p>\n");
      out.write("\t\t\t\t<ol>\n");
      out.write("\t\t\t\t\t<li>百度: <a href=\"https://www.baidu.com\" target=\"_blank\">www.baidu.com</a></li>\n");
      out.write("\t\t\t\t\t<li>cd 沈阳工业大学官网: <a href=\"http://www.sut.edu.cn/\" target=\"_blank\">www.sut.edu.cn</a></li>\n");
      out.write("\t\t\t\t\t<li>SUTACM: <a href=\"https://acm.sut.edu.cn\" target=\"_blank\">acm.sut.edu.cn</a></li>\n");
      out.write("\t\t\t\t\t<li>SUTOJ: <a href=\"http://sutoj.cwengo.com/\" target=\"_blank\">sutoj.cwengo.com</a></li>\n");
      out.write("\t\t\t\t\t<li>HDUOJ: <a href=\"http://acm.hdu.edu.cn/\" target=\"_blank\">acm.hdu.edu.cn </a></li>\n");
      out.write("\t\t\t\t\t<li>POJ: <a href=\"http://poj.org/\" target=\"_blank\">poj.org</a></li>\n");
      out.write("\t\t\t\t\t<li>cwen博客: <a href=\"http://www.cwengo.com/\" target=\"_blank\">cwengo.com</a></li>\n");
      out.write("\t\t\t\t</ol>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"meta\">\n");
      out.write("\t\t\t\t<p><a>2015-10-17 15:00</a></p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</div>\n");
      out.write("<script type=\"text/javascript\" class=\"autoinsert\" src=\"js/jquery-1.2.6.min.js\"></script> \n");
      out.write("<script src=\"js/snowfall.jquery.js\"></script> \n");
      out.write("<script>\n");
      out.write("        $(document).snowfall('clear');\n");
      out.write("        $(document).snowfall({\n");
      out.write("            image: \"images/huaban.png\",\n");
      out.write("            flakeCount:30,\n");
      out.write("            minSize: 5,\n");
      out.write("            maxSize: 22\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("<!-- 站长统计 -->\n");
      out.write("<script type=\"text/javascript\">var cnzz_protocol = ((\"https:\" == document.location.protocol) ? \" https://\" : \" http://\");document.write(unescape(\"%3Cspan id='cnzz_stat_icon_1256817075'%3E%3C/span%3E%3Cscript src='\" + cnzz_protocol + \"s95.cnzz.com/z_stat.php%3Fid%3D1256817075%26show%3Dpic' type='text/javascript'%3E%3C/script%3E\"));</script>\n");
      out.write("<!-- 站长统计结束 -->\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
